### ISSUE TITLE
No module named 'pycocotools._mask'

### ISSUE THREAD

**Issue by AvRuLE** [endernewton/tf-faster-rcnn#106]
Hi, while running the test script ./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101 i get the following error

Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from datasets.factory import get_imdb
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../lib/datasets/factory.py", line 15, in <module>
    from datasets.coco import coco
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../lib/datasets/coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../data/coco/PythonAPI/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../data/coco/PythonAPI/pycocotools/mask.py", line 5, in <module>
    import pycocotools._mask as _mask
ImportError: No module named 'pycocotools._mask'
Command exited with non-zero status 1
0.35user 0.24system 0:00.36elapsed 166%CPU (0avgtext+0avgdata 133356maxresident)k
0inputs+40outputs (0major+23441minor)pagefaults 0swaps

It seems i am unable to import cython module _mask.pyx but i have cython 0.25.2 installed.
On adding 
import pyximport
pyximport.install()

at the start of mask.py I am able to import _mask.pyx module but then i am getting the following error.

/usr/include/python3.5m/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^
/home/kist-iit2/.pyxbld/temp.linux-x86_64-3.5/pyrex/pycocotools/_mask.c:437:21: fatal error: maskApi.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from datasets.factory import get_imdb
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../lib/datasets/factory.py", line 15, in <module>
    from datasets.coco import coco
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../lib/datasets/coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../data/coco/PythonAPI/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/media/kist-iit2/421e12ca-0f68-44d8-8b26-dd6fd0619902/kist-iit2/Codes/Tensorflow/Faster_RCNN/tf-faster-rcnn/tools/../data/coco/PythonAPI/pycocotools/mask.py", line 5, in <module>
    import pycocotools._mask as _mask
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 445, in load_module
    language_level=self.language_level)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 232, in load_module
    raise exc.with_traceback(tb)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 216, in load_module
    inplace=build_inplace, language_level=language_level)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyximport.py", line 192, in build_module
    reload_support=pyxargs.reload_support)
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/pyximport/pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 338, in run
    self.build_extensions()
  File "/home/kist-iit2/.virtualenvs/cv/lib/python3.5/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python3.5/distutils/command/build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.5/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib/python3.5/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
ImportError: Building module pycocotools._mask failed: ["distutils.errors.CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1\n"]
Command exited with non-zero status 1
0.53user 0.40system 0:00.52elapsed 181%CPU (0avgtext+0avgdata 134828maxresident)k
0inputs+48outputs (0major+36427minor)pagefaults 0swaps

Can anyone please let me know the problem. I am unable to find a way to fix it.
Thanks you.

**Comment by endernewton** [comment]
you need to get the coco lib.

**Comment by AvRuLE** [comment]
Hi, Sorry for replying late. I have installed coco lib following the steps given in readme page, but still i get am getting this error. Can you please help me out with it.

**Comment by LeeKyungMoon** [comment]
I think you need to run the command 'make' at the directory PythonAPI of coco if you use python.
