### ISSUE TITLE
ValueError: operands could not be broadcast together

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#115]
I am trying to run faster rcnn on a custom dataset. After 5000 iterations suddenly this error shows up:

```
Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 267, in train_net
    sw.train_model(sess, max_iters)
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 198, in train_model
    self.snapshot(sess, iter)
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 61, in snapshot
    sess.run(net.bbox_weights_assign, feed_dict={net.bbox_weights: orig_0 * np.tile(self.bbox_stds, (weights_shape[0], 1))})
ValueError: operands could not be broadcast together with shapes (4096,84) (4096,40) 
```

My images are of size 1024*1024.

**Comment by endernewton** [comment]
does not seem you are using this repo. closing.
