### ISSUE TITLE
Trying to set TRAIN.RPN_POSITIVE_WEIGHT to a value other than  -1  .

### ISSUE THREAD

**Issue by SamyMe** [endernewton/tf-faster-rcnn#119]
Anyone got into this problem trying to set **TRAIN.RPN_POSITIVE_WEIGHT** to a value other than **-1**  ?

```
Traceback (most recent call last):
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/layer_utils/anchor_target_layer.py", line 108, in anchor_target_layer
    np.sum(labels == 0))
ZeroDivisionError: float division by zero
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/model/train_val.py", line 383, in train_net
    sw.train_model(sess, max_iters)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/model/train_val.py", line 263, in train_model
    self.net.train_step(sess, blobs, train_op, print_debug=print_debug)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/nets/network.py", line 382, in train_step
    feed_dict=feed_dict)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
         [[Node: vgg_16/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_score/BiasAdd/_115, _recv_Placeholder_2_0, _recv_Placeholder_1_0, vgg_16/anchor/PyFunc/input_3, vgg_16/ANCHOR_default/generate_anchors, vgg_16/anchor/PyFunc/input_5)]]
         [[Node: vgg_16/anchor/PyFunc/_129 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_406_vgg_16/anchor/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'vgg_16/anchor/PyFunc', defined at:
  File "tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/model/train_val.py", line 383, in train_net
    sw.train_model(sess, max_iters)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/model/train_val.py", line 106, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/nets/network.py", line 307, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 67, in build_network
    rpn_labels = self._anchor_target_layer(rpn_cls_score, "anchor")
  File "/home/blur/Documents/git/tf-faster-rcnn/tools/../lib/nets/network.py", line 151, in _anchor_target_layer
    [tf.float32, tf.float32, tf.float32, tf.float32])
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/blur/Documents/virtualenv/tfenv/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)

```

**Comment by endernewton** [comment]
there seems no negative examples in the batch. i have never touched that option myself.
