### ISSUE TITLE
ValueError: Dimension 0 in both shapes must be equal, but are 2 and 1

### ISSUE THREAD

**Issue by Lafi** [endernewton/tf-faster-rcnn#13]
I was going to train on my data, but I got this error of the reshape problem when I called below function 
which is in the lib/nets/vgg16.py :

> rpn_cls_score_reshape = self._reshape_layer(rpn_cls_score, 2, "rpn_cls_score_reshape")

```
def _reshape_layer(self, bottom, num_dim, name):
    input_shape = tf.shape(bottom)
    with tf.variable_scope(name) as scope:
        # change the channel to the caffe format
        to_caffe = tf.transpose(bottom, [0,3,1,2])
        # then force it to have channel 2
        reshaped = tf.reshape(to_caffe, tf.concat(0, [[self._batch_size], [num_dim, -1], [input_shape[2]]]))
        # then swap the channel back
        to_tf = tf.transpose(reshaped, [0,2,3,1])
        return to_tf
```

It get something wrong in the dimension of tf.concat function inside the line:

> reshaped = tf.reshape(to_caffe, tf.concat(0, [[self._batch_size], [num_dim, -1], [input_shape[2]]]))

I'm not familiar with it. I wonder if you have any idea about solving this problem??
Below is the Trackback:

```
Traceback (most recent call last):
  File "./tools/trainval_vgg16_net.py", line 125, in <module>
    max_iters=args.max_iters)
  File "/tmp/caffe_update/tf-faster-rcnn/tools/../lib/model/train_val.py", line 323, in train_net
    sw.train_model(sess, max_iters)
  File "/tmp/caffe_update/tf-faster-rcnn/tools/../lib/model/train_val.py", line 110, in train_model
    tag='default', anchor_scales=anchors)
  File "/tmp/caffe_update/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 499, in create_architecture
    rois, cls_prob, bbox_pred = self._vgg16_from_imagenet(sess, training)
  File "/tmp/caffe_update/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 352, in _vgg16_from_imagenet
    rpn_cls_score_reshape = self._reshape_layer(rpn_cls_score, 2, "rpn_cls_score_reshape")
  File "/tmp/caffe_update/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 182, in _reshape_layer
    reshaped = tf.reshape(to_caffe, tf.concat(0, [[self._batch_size], [num_dim, -1], [input_shape[2]]]))
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1047, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 651, in convert_to_tensor
    as_ref=False)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 923, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 886, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2041, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2397, in create_op
    set_shapes_for_outputs(ret)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1757, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1707, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/.local/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 2 and 1
         From merging shape 1 with other shapes. for 'vgg16_default/rpn_cls_score_reshape/concat/concat_dim' (op: 'Pack') with input shapes: [1], [2], [1].
Command exited with non-zero status 1
```

**Comment by xinleipan** [comment]
change tf.concat(0, [[self._batch_size], [num_dim, -1], [input_shape[2]]]) to tf.concat([[self._batch_size], [num_dim, -1], [input_shape[2]]], 0)

**Comment by Lafi** [comment]
Thanks you @xinleipan ! With you suggestion, everything goes right!

Your answer remind me that I had read in an old version API document of tensorflow.
And I have found the new version API r1.0 has change the parameter order in the [tf.concat](https://www.tensorflow.org/api_docs/python/tf/concat) function.

Again. Thank you for your help! : )

**Comment by endernewton** [comment]
Yes, you can see a pull request trying to address that version issue, but I havent tested myself yet.

**Comment by Lafi** [comment]
@endernewton I fixed the version issue manually. Good news is that just need to fix two functions in vgg.py

1.  tf.concat
old version:
`tf.concat(axis, values , name='concat')`
new version:
`tf.concat(values, axis, name='concat')`

In tf.concat case, do like what @xinleipan said, changing the parameters order of "axis" and "values" will be fine.

2. tf.nn.sparse_softmax_cross_entropy_with_logits
old version:
`tf.nn.sparse_softmax_cross_entropy_with_logits(logits, labels, name=None)`
new version:
`tf.nn.sparse_softmax_cross_entropy_with_logits(_sentinel=None, labels=None, logits=None, name=None)`

In tf.nn.sparse_softmax_cross_entropy_with_logits case, have to assign parameter fields in the new version. Exmaple:
`tf.nn.sparse_softmax_cross_entropy_with_logits(BBB_logits, AAA_labels) `
to 
`tf.nn.sparse_softmax_cross_entropy_with_logits(labels = AAA_labels, logits = BBB_logits)`

Hope this could help others.
Thanks again for both you two replying this thread!
