### ISSUE TITLE
porblems for tensorflow 1.1

### ISSUE THREAD

**Issue by Jiakui** [endernewton/tf-faster-rcnn#134]
I am running the problem on tf  **'1.1.0-rc2'**

There is an error about resnet_utils:

Solving...
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/media/veilytech/Model/tf-faster-rcnn/tools/../lib/model/train_val.py", line 336, in train_net
    sw.train_model(sess, max_iters)
  File "/media/veilytech/Model/tf-faster-rcnn/tools/../lib/model/train_val.py", line 105, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/media/veilytech/Model/tf-faster-rcnn/tools/../lib/nets/network.py", line 306, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/media/veilytech/Model/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 155, in build_network
    scope=self._resnet_scope)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 212, in resnet_v1
    net = resnet_utils.stack_blocks_dense(net, blocks, output_stride)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_utils.py", line 216, in stack_blocks_dense
    net = block.unit_fn(net, rate=1, **unit)
TypeError: bottleneck() argument after ** must be a mapping, not tuple
Command exited with non-zero status 1
3.97user 0.36system 0:04.35elapsed 99%CPU (0avgtext+0avgdata 404108maxresident)k
0inputs+40outputs (0major+68855minor)pagefaults 0swaps

**Comment by zbpjlc** [comment]
I have the same problem with GPU, but I can run with CPU

**Comment by endernewton** [comment]
haven't tested on 1.1 yet. let me test it out in some time.

**Comment by ilchemla** [comment]
Also happening with:
```
Name: tensorflow-gpu
Version: 1.2.0
```

**Comment by freezingmolly** [comment]
I have the same problem with tensorflow 1.2. It works well when changed to 1.0.

**Comment by bhack** [comment]
Recently Faster RCNN models are also officially available in https://github.com/tensorflow/models/tree/master/object_detection

**Comment by auroua** [comment]
The stack_blocks_dense function in slim have changed.
The code in tensorflow v1.0:
``` python
net = block.unit_fn(
                net,
                depth=unit_depth,
                depth_bottleneck=unit_depth_bottleneck,
                stride=unit_stride,
rate=1)
```
The code in tensorflow v1.2:
```python
net = block.unit_fn(net, rate=1, **unit)
```
Because of this change, you should change the blocks definition in ```resnet_v1.py```. 
You can reference the offical implementation in [resnet-v1](https://github.com/tensorflow/models/blob/master/slim/nets/resnet_v1.py). You just need add a function ```resnet_v1_block``` and change the bolcks definition to 
```python
      blocks = [
          resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
          resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
          resnet_v1_block('block3', base_depth=256, num_units=23, stride=1),
          resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
      ]
```

**Comment by svdalv0313** [comment]
I have the same problem in 1.2

**Comment by jackytu256** [comment]
@svdalv0313,
 it works if you follow auroua's instruction.
 Firstly, you need to add resnet_v1_block

  ```python
  def resnet_v1_block(self,scope, base_depth, num_units, stride):
      """Helper function for creating a resnet_v1 bottleneck block.
      Args:
        scope: The scope of the block.
        base_depth: The depth of the bottleneck layer for each unit.
        num_units: The number of units in the block.
        stride: The stride of the block, implemented as a stride in the last unit.
          All other units have stride=1.
      Returns:
        A resnet_v1 bottleneck block.
      """
      return resnet_utils.Block(scope, resnet_v1.bottleneck, [{
          'depth': base_depth * 4,
          'depth_bottleneck': base_depth,
          'stride': 1
      }] * (num_units - 1) + [{
          'depth': base_depth * 4,
          'depth_bottleneck': base_depth,
          'stride': stride
    }])
```
and then change the definitions of blocks for resnet50,101,152


  ```python  
    if self._num_layers == 50:
      blocks = [
          self.resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
          self.resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
          self.resnet_v1_block('block3', base_depth=256, num_units=6, stride=2),
          self.resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
      ]
    elif self._num_layers == 101:
      blocks = [
          self.resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
          self.resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
          self.resnet_v1_block('block3', base_depth=256, num_units=23, stride=2),
          self.resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
      ]
    elif self._num_layers == 152:
      blocks = [
          self.resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
          self.resnet_v1_block('block2', base_depth=128, num_units=8, stride=2),
          self.resnet_v1_block('block3', base_depth=256, num_units=36, stride=2),
          self.resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
      ]```

**Comment by jackytu256** [comment]
Hi @auroua ,
  I was trying to modify code based on your advice , but it doesn't work
  Here is the error code
```python
 InvalidArgumentError (see above for traceback): exceptions.ValueError: cannot reshape array of size 22800 into shape (1,19,25,12)
         [[Node: resnet_v1_152_3/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](resnet_v1_152_3/rpn_cls_score/BiasAdd, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, resnet_v1_152_3/anchor/PyFunc/input_3, resnet_v1_152_3/ANCHOR_default/generate_anchors, resnet_v1_152_3/anchor/PyFunc/input_5)]]
```
Any idea to solve this ?

Thanks

**Comment by FPerezHernandez92** [comment]
I have the same problem in tensorflow 1.2

**Comment by auroua** [comment]
@jackytu256 
I can run the model without any error.
The author pre-trained model is based on coco, so you should modify the ```demo.py``` as follows:
1.
```python
CLASSES = ('__background__', 'person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat',
           'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse',
           'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase',
           'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard',
           'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana',
           'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
           'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
           'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
           'hair drier', 'toothbrush')
```
2.
```python
NETS = {'vgg16': ('vgg16_faster_rcnn_iter_70000.ckpt',),'res101': ('res101_faster_rcnn_iter_110000.ckpt',), 'res152':('res152_faster_rcnn_iter_1190000.ckpt',)}
DATASETS= {'pascal_voc': ('voc_2007_trainval',),'pascal_voc_0712': ('voc_2007_trainval+voc_2012_trainval',),'coco_2014':('coco_2014_train',)}
```
The location of pre-trained model is ``` /xxxx  yourself location  xxxx/tf-faster-rcnn/output/res152/coco_2014_train/default/res152_faster_rcnn_iter_1190000.ckpt.xxxxx```
3.
``` python
    elif demonet == 'res152':
        net = resnetv1(batch_size=1, num_layers=152)

    net.create_architecture(sess, "TEST", 81,
                          tag='default', anchor_scales=[4, 8, 16, 32])
```
After the above modification, you should modify the ```resnet_v1.py```:
```python
    elif self._num_layers == 152:
      blocks = [
          resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
          resnet_v1_block('block2', base_depth=128, num_units=8, stride=2),
          resnet_v1_block('block3', base_depth=256, num_units=36, stride=1),
          resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
      ]
```
I hope this will helpful.

**Comment by moiseevigor** [comment]
End up i this issue with the same problem, at the end the final diff

```
100c100,102
<     bottleneck = resnet_v1.bottleneck
---
> 
>     # /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py
>     resnet_v1_block = resnet_v1.resnet_v1_block
104,111c106,109
<         resnet_utils.Block('block1', bottleneck,
<                            [(256, 64, 1)] * 2 + [(256, 64, 2)]),
<         resnet_utils.Block('block2', bottleneck,
<                            [(512, 128, 1)] * 3 + [(512, 128, 2)]),
<         # Use stride-1 for the last conv4 layer
<         resnet_utils.Block('block3', bottleneck,
<                            [(1024, 256, 1)] * 5 + [(1024, 256, 1)]),
<         resnet_utils.Block('block4', bottleneck, [(2048, 512, 1)] * 3)
---
>           resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
>           resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
>           resnet_v1_block('block3', base_depth=256, num_units=6, stride=1),
>           resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
115,122c113,116
<         resnet_utils.Block('block1', bottleneck,
<                            [(256, 64, 1)] * 2 + [(256, 64, 2)]),
<         resnet_utils.Block('block2', bottleneck,
<                            [(512, 128, 1)] * 3 + [(512, 128, 2)]),
<         # Use stride-1 for the last conv4 layer
<         resnet_utils.Block('block3', bottleneck,
<                            [(1024, 256, 1)] * 22 + [(1024, 256, 1)]),
<         resnet_utils.Block('block4', bottleneck, [(2048, 512, 1)] * 3)
---
>           resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
>           resnet_v1_block('block2', base_depth=128, num_units=4, stride=2),
>           resnet_v1_block('block3', base_depth=256, num_units=23, stride=1),
>           resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
126,133c120,123
<         resnet_utils.Block('block1', bottleneck,
<                            [(256, 64, 1)] * 2 + [(256, 64, 2)]),
<         resnet_utils.Block('block2', bottleneck,
<                            [(512, 128, 1)] * 7 + [(512, 128, 2)]),
<         # Use stride-1 for the last conv4 layer
<         resnet_utils.Block('block3', bottleneck,
<                            [(1024, 256, 1)] * 35 + [(1024, 256, 1)]),
<         resnet_utils.Block('block4', bottleneck, [(2048, 512, 1)] * 3)
---
>           resnet_v1_block('block1', base_depth=64, num_units=3, stride=2),
>           resnet_v1_block('block2', base_depth=128, num_units=8, stride=2),
>           resnet_v1_block('block3', base_depth=256, num_units=36, stride=1),
>           resnet_v1_block('block4', base_depth=512, num_units=3, stride=1),
```

**Comment by s2244521** [comment]
I also have this problem in my code when I do the testing process to get the activation value from a 1*1*512 layer.
I train a network and need to get the activation value from this trained network but it is no problem when I use the training data to get the value but the problem occured in testing data.
