### ISSUE TITLE
Problems with demo.py

### ISSUE THREAD

**Issue by namngu** [endernewton/tf-faster-rcnn#166]
Hello,

i am really desperate to get the demo.py of this repository to run... i am using Tensorflow 1.2.1 on Windows with CPU only. All I want is try to get this demo.py to run so that i get some test-detections. After tiring myself out with problems regarding windows and cpu-only-mode I finally get an Error Message, which seems to come from Tensorflow, when I just start demo.py:

My best interpretation is that there might be something wrong with the feed_dict, since there seems to be some kind of error with that codeline? (I manually enclosed the error-code-line with # below). Does anybody have the same problem? Is there anyone who can help me to interpretate this error-msg? I am thankful for every answer since i am really lost at moment.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/004545.jpg
Traceback (most recent call last):

  File "<ipython-input-43-c66249674231>", line 1, in <module>
    runfile('C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools/demo.py', wdir='C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools')

  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)

  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools/demo.py", line 170, in <module>
    scores, boxes = im_detect(sess, net, im)

  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\model\test.py", line 94, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
##########
  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\nets\network.py", line 420, in test_image
    feed_dict=feed_dict)
##########
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)

  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 997, in _run
    feed_dict_string, options, run_metadata)

  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1132, in _do_run
    target_list, options, run_metadata)

  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)

UnknownError: SystemError: ..\Objects\moduleobject.c:449: bad argument to internal function
	 [[Node: resnet_v1_101_3/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_23", _device="/job:localhost/replica:0/task:0/cpu:0"](resnet_v1_101_3/rpn_cls_prob/transpose_1, resnet_v1_101_3/rpn_bbox_pred/BiasAdd, _arg_Placeholder_1_0_1, resnet_v1_101_3/rois/PyFunc/input_3, resnet_v1_101_3/rois/PyFunc/input_4, resnet_v1_101_3/ANCHOR_default/generate_anchors, resnet_v1_101_3/rois/PyFunc/input_6)]]

Caused by op 'resnet_v1_101_3/rois/PyFunc', defined at:
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 231, in <module>
    main()
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 227, in main
    kernel.start()
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\ipykernel\zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\IPython\core\interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\IPython\core\interactiveshell.py", line 2808, in run_ast_nodes
    if self.run_code(code, result):
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\IPython\core\interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-43-c66249674231>", line 1, in <module>
    runfile('C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools/demo.py', wdir='C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools')
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/ProgramFiles/Git_Repositories/tf-faster-rcnn/tools/demo.py", line 149, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\nets\network.py", line 363, in create_architecture
    rois, cls_prob, bbox_pred = self._build_network(sess, training)
  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\nets\resnet_v1.py", line 146, in _build_network
    rois = self._region_proposal(net_conv, is_training, initializer)
  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\nets\network.py", line 294, in _region_proposal
    rois, _ = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred, "rois")
  File "C:\ProgramFiles\Git_Repositories\tf-faster-rcnn\tools\..\lib\nets\network.py", line 110, in _proposal_layer
    [tf.float32, tf.float32])
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\gen_script_ops.py", line 38, in _py_func
    name=name)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "C:\ProgramFiles\Anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): SystemError: ..\Objects\moduleobject.c:449: bad argument to internal function
	 [[Node: resnet_v1_101_3/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_23", _device="/job:localhost/replica:0/task:0/cpu:0"](resnet_v1_101_3/rpn_cls_prob/transpose_1, resnet_v1_101_3/rpn_bbox_pred/BiasAdd, _arg_Placeholder_1_0_1, resnet_v1_101_3/rois/PyFunc/input_3, resnet_v1_101_3/rois/PyFunc/input_4, resnet_v1_101_3/ANCHOR_default/generate_anchors, resnet_v1_101_3/rois/PyFunc/input_6)]]

**Comment by namngu** [comment]
I have somewhat found a solution for my problem. I installed the same Repository including Cython etc. on another Computer with Windows and it happened to work there. My own conclusion: the code is alright, i did not alter anything about the code; however there may be some differences in building the cython modules on different computers due to different configurations (probably of the c compiler).
