### ISSUE TITLE
build fail on windows7-64bit

### ISSUE THREAD

**Issue by concerttttt** [endernewton/tf-faster-rcnn#169]
I am seeing the following error when trying to use pip to install numexpr. Please let me know if there is anything I can supply to help solve this bug. Thanks.

The main error I am getting is:
`AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'`

Output:
`C:\Users\Administrator.ASM.000\tf-faster-rcnn\lib>python setup.py build
include : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\include
lib64 : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\lib\x64
home : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
nvcc : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin
running build
running build_ext
Traceback (most recent call last):
  File "setup.py", line 152, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "D:\Ana3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "D:\Ana3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Ana3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Ana3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "D:\Ana3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "D:\Ana3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Ana3\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in r
un
    _build_ext.build_ext.run(self)
  File "D:\Ana3\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 107, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 80, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
`

**Comment by engineer1109** [comment]
So stupid。
Windows 7 has so compiler

**Comment by concerttttt** [comment]
So?
Guess you have got the solution to this problem, duh?

**Comment by engineer1109** [comment]
@concerttttt   This code needs to run on linux system, like ubuntu 16.04.
Windows don't have so-compiler, and so-file exists in the linux.

**Comment by lovenets** [comment]
I passed it like this:     if hasattr(self, 'compiler_so') : # add by hwx at 20180408
        default_compiler_so = self.compiler_so
