### ISSUE TITLE
KeyError: 'flipped' Command exited with non-zero status 1

### ISSUE THREAD

**Issue by hadi-ghnd** [endernewton/tf-faster-rcnn#196]
I am trying to add some data augmentation like **vertical flipping** and  **rotation** to the model. I have added the functions to the **imdb.py** and added to [minibatch.py](https://github.com/endernewton/tf-faster-rcnn/blob/9336b01e5208a1640bd30fef773137c54b0c2cb9/lib/roi_data_layer/minibatch.py#L61) like this:
```

  for i in range(num_images):
    im = cv2.imread(roidb[i]['image'])
    #num_rows, num_cols = im.shape[:2]
    print('i: {}'.format(i))
    if roidb[i]['flipped']:
      im = im[:, ::-1, :]
    if roidb[i]['vflipped']:
      im = im[::-1, :, :]
    if roidb[i]['rotated']:
      im = np.rot90(im, k=1)
    target_size = cfg.TRAIN.SCALES[scale_inds[i]]
    im, im_scale = prep_im_for_blob(im, cfg.PIXEL_MEANS, target_size,
                    cfg.TRAIN.MAX_SIZE)
    im_scales.append(im_scale)
    processed_ims.append(im)
```
The roi generation goes well, but I get this error:

```
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 145, in <module>
    max_iters=args.max_iters)
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/model/train_val.py", line 353, in train_net
    sw.train_model(sess, max_iters)
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/model/train_val.py", line 219, in train_model
    blobs = self.data_layer.forward()
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/roi_data_layer/layer.py", line 87, in forward
    blobs = self._get_next_minibatch()
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/roi_data_layer/layer.py", line 83, in _get_next_minibatch
    return get_minibatch(minibatch_db, self._num_classes)
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/roi_data_layer/minibatch.py", line 30, in get_minibatch
    im_blob, im_scales = _get_image_blob(roidb, random_scale_inds)
  File "/home/hadi/Software/tensorflow/vedai-test/tools/../lib/roi_data_layer/minibatch.py", line 66, in _get_image_blob
    if roidb[i]['flipped']:
KeyError: 'flipped'
Command exited with non-zero status 1
9.78user 1.97system 0:11.98elapsed 98%CPU (0avgtext+0avgdata 2856948maxresident)k
0inputs+1608outputs (0major+457693minor)pagefaults 0swaps
```
What can I do to solve this issue?
thanks

**Comment by paulcx** [comment]
@hadi-ghnd How did you manage the rotation functions in imdb.py?

**Comment by hadi-ghnd** [comment]
@paulcx I have only added a function for 180 degree rotation:

```
def append_rotated_images(self):
    num_images = self.num_images
    widths = self._get_widths()
    for i in range(num_images):
      boxes = self.roidb[i]['boxes'].copy()
      oldx1 = boxes[:, 0].copy()
      oldx2 = boxes[:, 2].copy()
	  oldy1 = boxes[:, 1].copy()
      oldy2 = boxes[:, 3].copy()
	  
	  #dx = oldx2-oldx1
	  #dy = oldy2-oldy1
	  
	  #xc = oldx2 - dx/2
	  #yc = oldy2 - dy/2
	  	   
      boxes[:, 0] = oldy1 - 1
      boxes[:, 2] = oldy2 - 1
      boxes[:, 1] = oldx2 - 1
      boxes[:, 3] = oldx1 - 1
	  
      assert (boxes[:, 2] >= boxes[:, 0] and boxes[:, 3] >= boxes[:, 1]).all()
      entry = {'boxes': boxes,
               'gt_overlaps': self.roidb[i]['gt_overlaps'],
               'gt_classes': self.roidb[i]['gt_classes'],
               'rotated': True}
      self.roidb.append(entry)
    self._image_index = self._image_index * 4
```

I have added something for rotation near every flipping parts, But it gives this error.

**Comment by paulcx** [comment]
@hadi-ghnd It looks cool here. I'm wondering if something goes wrong where the function is called.

**Comment by satya2550** [comment]
@hadi-ghnd 
Hi, are you able to resolve the error for handling 180 degree rotation.
I also want to do the similar thing on my custom data set

**Comment by John1231983** [comment]
@hadi-ghnd: Could you please share how did you add rotation to augmentation. It is very helpful for me
