### ISSUE TITLE
Invalid argument

### ISSUE THREAD

**Issue by xiaomeng-feng** [endernewton/tf-faster-rcnn#199]
Hi, guys, I had a problem in the following. Could someone can help me?

Demo for data/demo/000456.jpg
2017-08-24 10:53:53.037007: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: exceptions.TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./tools/demo.py", line 154, in <module>
    demo(sess, net, im_name)
  File "./tools/demo.py", line 86, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/Users/von/anaconda/tf-faster-rcnn/tools/../lib/model/test.py", line 93, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/Users/von/anaconda/tf-faster-rcnn/tools/../lib/nets/network.py", line 445, in test_image
    feed_dict=feed_dict)
  File "/Users/von/anaconda/envs/tensorflow2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/Users/von/anaconda/envs/tensorflow2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/von/anaconda/envs

**Comment by endernewton** [comment]
check the easydict installation? i use 1.6

**Comment by zhme** [comment]
I have the same problem, how do you solve it？
