### ISSUE TITLE
Error in `python': corrupted size vs. prev_size: 0x0000000000ec3240

### ISSUE THREAD

**Issue by zdm123** [endernewton/tf-faster-rcnn#220]
I only do the 25000 iteration, and test the model, but have the following problem. Do you have any ideal what is the problem?
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 117, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home2/sdin7632/shanshan/tf-faster-rcnn-r1.0/tools/../lib/model/test.py", line 196, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home2/sdin7632/shanshan/tf-faster-rcnn-r1.0/tools/../lib/datasets/pascal_voc.py", line 281, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home2/sdin7632/shanshan/tf-faster-rcnn-r1.0/tools/../lib/datasets/pascal_voc.py", line 244, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home2/sdin7632/shanshan/tf-faster-rcnn-r1.0/tools/../lib/datasets/voc_eval.py", line 134, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '1'
*** Error in `python': corrupted size vs. prev_size: 0x0000000000ec3240 ***
Command terminated by signal 6
198.54user 187.98system 8:45.24elapsed 73%CPU (0avgtext+0avgdata 1548152maxresident)k
406352inputs+1688outputs (0major+1913505minor)pagefaults 0swaps

**Comment by John1231983** [comment]
@zdm123 : Have you solve this issue? I have same issue as you

**Comment by Hsy1996** [comment]
@zdm123  I have the same problem. Did you solve it ?

**Comment by AliceLcz** [comment]
I also have the same problem. Following is my logs:
li@li-RESCUER-Y720-15IKB:~/tf-faster-rcnn$ ./experiments/scripts/test_faster_rcnn.sh 0 pascal_voc vgg16
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ GPU_ID=0
+ DATASET=pascal_voc
+ NET=vgg16
+ array=($@)
+ len=3
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case ${DATASET} in
+ TRAIN_IMDB=voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ ITERS=10000
+ ANCHORS='[8,16,32]'
+ RATIOS='[0.5,1,2]'
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/test_vgg16_voc_2007_trainval_.txt.2018-03-09_09-06-01
+ exec
++ tee -a experiments/logs/test_vgg16_voc_2007_trainval_.txt.2018-03-09_09-06-01
+ echo Logging output to experiments/logs/test_vgg16_voc_2007_trainval_.txt.2018-03-09_09-06-01
Logging output to experiments/logs/test_vgg16_voc_2007_trainval_.txt.2018-03-09_09-06-01
+ set +x
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python ./tools/test_net.py --imdb voc_2007_test --model output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_10000.ckpt --cfg experiments/cfgs/vgg16.yml --net vgg16 --set ANCHOR_SCALES '[8,16,32]' ANCHOR_RATIOS '[0.5,1,2]'
/home/li/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Called with args:
Namespace(cfg_file='experiments/cfgs/vgg16.yml', comp_mode=False, imdb_name='voc_2007_test', max_per_image=100, model='output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_10000.ckpt', net='vgg16', set_cfgs=['ANCHOR_SCALES', '[8,16,32]', 'ANCHOR_RATIOS', '[0.5,1,2]'], tag='')
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'DATA_DIR': '/home/li/tf-faster-rcnn/data',
 'EXP_DIR': 'vgg16',
 'MATLAB': 'matlab',
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/li/tf-faster-rcnn',
 'RPN_CHANNELS': 512,
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 256,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'vgg16_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
2018-03-09 09:06:08.997773: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-09 09:06:08.997840: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-09 09:06:08.997886: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-03-09 09:06:08.997915: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-03-09 09:06:08.997939: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-03-09 09:06:09.150783: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-09 09:06:09.151227: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1060
major: 6 minor: 1 memoryClockRate (GHz) 1.6705
pciBusID 0000:01:00.0
Total memory: 5.94GiB
Free memory: 5.48GiB
2018-03-09 09:06:09.151241: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-03-09 09:06:09.151246: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-03-09 09:06:09.151256: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060, pci bus id: 0000:01:00.0)
Loading model check point from output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_10000.ckpt
Loaded.
im_detect: 1/10 2.103s 0.001s
im_detect: 2/10 1.964s 0.001s
im_detect: 3/10 1.944s 0.001s
im_detect: 4/10 2.057s 0.001s
im_detect: 5/10 2.067s 0.001s
im_detect: 6/10 2.094s 0.002s
im_detect: 7/10 2.008s 0.002s
im_detect: 8/10 2.046s 0.001s
im_detect: 9/10 2.026s 0.001s
im_detect: 10/10 1.956s 0.001s
Evaluating detections
Writing aeroplane VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/li/tf-faster-rcnn/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/li/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 285, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/li/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 248, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "/home/li/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 135, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '000017'
Command exited with non-zero status 1
22.08user 6.63system 0:30.15elapsed 95%CPU (0avgtext+0avgdata 1857444maxresident)k
1296inputs+88outputs (6major+475117minor)pagefaults 0swaps

000017 is a image name of my test set, did you solve it?

**Comment by dnd88** [comment]
Hi, I also had the similar problem. 
In my case, there were two data-sets(directory) in the same directory. (/tf-faster-rcnn/data/VOCdevkit2007/)
One was face data, the other one was license plate data.
When I wanted to test about license plate detection, I faced the similar problem. 

When I printed "recs" by "print(recs)" at
(File "/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 134, in voc_eval),
it didn't read license plate data, but read face data. 
So I just remove the directory for face data, it works after that.
