### ISSUE TITLE
ImportError: cannot import name resnet_v1

### ISSUE THREAD

**Issue by backtime92** [endernewton/tf-faster-rcnn#224]
hi,Is there anyone have this problem?

Traceback (most recent call last):
  File "./tools/test_net.py", line 20, in <module>
    from nets.resnet_v1 import resnetv1
  File "/home/amax/Documents/test/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 15, in <module>
    from tensorflow.contrib.slim.python.slim.nets import resnet_v1
  File "/home/amax/anaconda3/envs/yanhai/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/nets/resnet_v1.py", line 60, in <module>
    from tensorflow.contrib.slim.nets import resnet_utils
  File "/home/amax/anaconda3/envs/yanhai/lib/python2.7/site-packages/tensorflow/contrib/slim/nets.py", line 40, in <module>
    from tensorflow.contrib.slim.python.slim.nets import resnet_v1

**Comment by endernewton** [comment]
is your tf version 1.2+?

**Comment by hongrui16** [comment]
my tf version is 0.12.1
it reports that "ImportError: cannot import name resnet_v1" when I load test_faster_rcnn.sh
i add a new PYTHONPATH environment variable,but it still failed.
thx

**Comment by VisintZJ** [comment]
I also have this problem and my tf_version is 1.1 with GPU. Is there anyone can solve this problem? thx.

**Comment by backtime92** [comment]
tf_version 1.2 can solve the error

**Comment by ATPNazlit** [comment]
+1 I have the same issue.. tf_1.2 did not work out

**Comment by backtime92** [comment]
i think maybe you can reinstall tf with version 1.2+,i solve this problem with the approach

**Comment by hongrui16** [comment]
i find a solution
do a little change

tf-faster-rcnn/lib/nets/resnet_v1.py LINE 15

#from tensorflow.contrib.slim.python.slim.nets import resnet_v1
import resnet_v1

it works

**Comment by krsandeep98** [comment]
https://stackoverflow.com/questions/40957286/attributeerror-module-tensorflow-contrib-slim-has-no-attribute-nets
This works for me on tensorflow version 1.15.
