### ISSUE TITLE
input shapes not equal?

### ISSUE THREAD

**Issue by Data-drone** [endernewton/tf-faster-rcnn#24]
I am trying the demo code on pascal_voc 
`./experiments/scripts/test_vgg16.sh $GPU_ID pascal_voc`

but I get:

`Traceback (most recent call last):
  File "./tools/test_vgg16_net.py", line 89, in <module>
    tag='default', anchor_scales=anchors)
  File "/home/brian/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 481, in create_architecture
    rois, cls_prob, bbox_pred = self._vgg16_from_imagenet(sess, training)
  File "/home/brian/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 350, in _vgg16_from_imagenet
    rpn_cls_score_reshape = self._reshape_layer(rpn_cls_score, 2, "rpn_cls_score_reshape")
  File "/home/brian/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 181, in _reshape_layer
    reshaped = tf.reshape(to_caffe, tf.concat([[self._batch_size], [num_dim, -1], [input_shape[2]]], 0))
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1075, in concat
    dtype=dtypes.int32).get_shape(
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 669, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 836, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 799, in _autopacking_helper
    return gen_array_ops._pack(elems_as_tensors, name=scope)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1975, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1617, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1568, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/brian/.local/lib/python3.5/site-packages/tensorflow/python/framework/common_shapes.py", line 675, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension 0 in both shapes must be equal, but are 2 and 1
	From merging shape 1 with other shapes. for 'vgg16_default/rpn_cls_score_reshape/concat/concat_dim' (op: 'Pack') with input shapes: [1], [2], [1].
`

any ideas?

**Comment by endernewton** [comment]
Maybe you can check the shape of tensors at _reshape_layer?

**Comment by endernewton** [comment]
Please update the tensorflow version. I heard this solved the problem.

**Comment by lyltencent** [comment]
@endernewton , Hi can you let us know which version of tensorflow are you using to run the code. 

Thanks,
