### ISSUE TITLE
remove pool4

### ISSUE THREAD

**Issue by yfnn** [endernewton/tf-faster-rcnn#245]
I'm using vgg16 convNet. When I remove the forth maxpooling layer, I got this error:
InvalidArgumentError (see above for traceback): exceptions.ValueError: operands could not be broadcast together with shapes (42300,1) (10716,1)

more details:
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 91, in <module>
    args = parse_args()
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/model/train_val.py", line 344, in train_net
    sw.train_model(sess, max_iters)
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/model/train_val.py", line 161, in train_model
    variables = tf.global_variables()
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/nets/network.py", line 432, in train_step
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: exceptions.ValueError: operands could not be broadcast together with shapes (42300,1) (10716,1) 
	 [[Node: vgg_16/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_prob/transpose_1/_161, vgg_16/rpn_bbox_pred/BiasAdd/_163, _arg_Placeholder_1_0_1, vgg_16/rois/PyFunc/input_3, vgg_16/rois/PyFunc/input_4, vgg_16/ANCHOR_default/generate_anchors, vgg_16/rois/PyFunc/input_6)]]
	 [[Node: gradients/loss_default/mul_grad/Shape/_125 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_386_gradients/loss_default/mul_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'vgg_16/rois/PyFunc', defined at:
  File "./tools/trainval_net.py", line 91, in <module>
    args = parse_args()
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/model/train_val.py", line 344, in train_net
    sw.train_model(sess, max_iters)
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/model/train_val.py", line 106, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/nets/network.py", line 356, in create_architecture
    rois, cls_prob, bbox_pred = self._build_network(sess, training)
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 54, in _build_network
    rois = self._region_proposal(net, is_training, initializer)
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/nets/network.py", line 280, in _region_proposal
    rois, roi_scores = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred, "rois")
  File "/home/yangfan/tf-faster-rcnn/tools/../lib/nets/network.py", line 100, in _proposal_layer
    rois, rpn_scores = tf.py_func(proposal_layer,
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 203, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 36, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): exceptions.ValueError: operands could not be broadcast together with shapes (42300,1) (10716,1) 
	 [[Node: vgg_16/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_prob/transpose_1/_161, vgg_16/rpn_bbox_pred/BiasAdd/_163, _arg_Placeholder_1_0_1, vgg_16/rois/PyFunc/input_3, vgg_16/rois/PyFunc/input_4, vgg_16/ANCHOR_default/generate_anchors, vgg_16/rois/PyFunc/input_6)]]
	 [[Node: gradients/loss_default/mul_grad/Shape/_125 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_386_gradients/loss_default/mul_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Why this happened?
Where should I modify?

**Comment by wanghao00** [comment]
Have you solved this proplem?
