### ISSUE TITLE
ValueError: No variables to save

### ISSUE THREAD

**Issue by PiroAntoine** [endernewton/tf-faster-rcnn#283]
Hello, 

I would like to create a dataset (the same way Pascal VOC) and train a res101 on it.

I wrote a cpp code to create my dataset and call the train_faster_rcnn.sh

But I meet this error : "ValueError: No variables to save"

Here is my log file :

+ echo Logging output to tf-faster-rcnn/experiments/logs/res101_voc_2007_trainval__res101.txt.2018-01-12_16-01-23
Logging output to tf-faster-rcnn/experiments/logs/res101_voc_2007_trainval__res101.txt.2018-01-12_16-01-23
+ set +x
+ '[' '!' -f tf-faster-rcnn/output/res101/voc_2007_trainval/default/res101_faster_rcnn_iter_70000.ckpt.index ']'
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python2 ./tf-faster-rcnn/tools/trainval_net.py --weight /home/antoine/Documents/RCNNProject/DataFolder/imagenet_weights/res101.ckpt
Called with args:
Namespace(cfg_file=None, imdb_name='voc_2007_trainval', imdbval_name='voc_2007_test', max_iters=70000, net='res50', set_cfgs=None, tag=None, weight='/home/antoine/Documents/RCNNProject/DataFolder/imagenet_weights/res101.ckpt')
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'DATA_DIR': '/home/antoine/Documents/RCNNProject/DataFolder/',
 'EXP_DIR': 'default',
 'MATLAB': 'matlab',
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn',
 'RPN_CHANNELS': 512,
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': False,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.1,
           'BIAS_DECAY': False,
           'DISPLAY': 10,
           'DOUBLE_BIAS': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [30000],
           'SUMMARY_INTERVAL': 180,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': True}
Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
wrote gt roidb to /home/antoine/Documents/RCNNProject/DataFolder/cache/voc_2007_trainval_gt_roidb.pkl
done
Preparing training data...
done
2348 roidb entries
Output will be saved to `/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn/output/default/voc_2007_trainval/default`
TensorFlow summaries will be saved to `/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn/tensorboard/default/voc_2007_trainval/default`
Loaded dataset `voc_2007_test` for training
Set proposal method: gt
Preparing training data...
wrote gt roidb to /home/antoine/Documents/RCNNProject/DataFolder/cache/voc_2007_test_gt_roidb.pkl
done
293 validation roidb entries
Filtered 0 roidb entries: 2348 -> 2348
Filtered 0 roidb entries: 293 -> 293
2018-01-12 16:01:26.192323: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Solving...
/home/antoine/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:96: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading initial model weights from /home/antoine/Documents/RCNNProject/DataFolder/imagenet_weights/res101.ckpt
Traceback (most recent call last):
  File "./tf-faster-rcnn/tools/trainval_net.py", line 139, in <module>
    max_iters=args.max_iters)
  File "/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn/tools/../lib/model/train_val.py", line 391, in train_net
    sw.train_model(sess, max_iters)
  File "/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn/tools/../lib/model/train_val.py", line 268, in train_model
    sess)
  File "/home/antoine/Documents/RCNNProject/project-build/tf-faster-rcnn/tools/../lib/model/train_val.py", line 201, in initialize
    restorer = tf.train.Saver(variables_to_restore)
  File "/home/antoine/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/antoine/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/antoine/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
Command exited with non-zero status 1
8.54user 1.10system 0:07.82elapsed 123%CPU (0avgtext+0avgdata 724440maxresident)k
0inputs+8320outputs (0major+174129minor)pagefaults 0swaps

Can someone tell me what can be going on ? :)

Thank you

**Comment by minda163** [comment]
Did you solve it？I have the same issue

**Comment by cnuzh** [comment]
> Did you solve it？I have the same issue
Hi, I have the same issue. Did you solve it?

**Comment by devendraswamy** [comment]
!python /content/drive/MyDrive/tf-faster-rcnn/tools/trainval_net.py --net vgg16 --weight /content/drive/MyDrive/tf-faster-rcnn/data/imagenet_weights/vgg16.ckpt --imdb voc_2007_trainval  --imdbval voc_2007_test  

please make sure the --net and --weight is vgg16 & vgg.ckpt are like this. thank you
