### ISSUE TITLE
No instances_valminusminival2014.json when training coco dataset

### ISSUE THREAD

**Issue by tensor-flower** [endernewton/tf-faster-rcnn#293]
I'm trying to run
```
./experiments/scripts/train_faster_rcnn.sh 0 coco res101
```
but I don't have this annotation file called instances_valminusminival2014.json. 

```
FileNotFoundError: [Errno 2] No such file or directory: '/media/tensorflower/ExtraDrive1/tf-faster-rcnn/data/coco/annotations/instances_valminusminival2014.json'
Command exited with non-zero status 1
```
I downloaded coco api and unzipped coco 14 datasets and annotation files into the data/coco directory. When I go to data/coco/annotations, indeed that .json is not there. I only have 
captions_train2014.json   instances_train2014.json         person_keypoints_val2014.json
captions_val2014.json     instances_val2014.json
image_info_test2014.json  person_keypoints_train2014.json

What am I missing here? Attached is my log.

```
+ echo Logging output to experiments/logs/res101_coco_2014_train+coco_2014_valminusminival__res101.txt.2018-02-04_14-10-46
Logging output to experiments/logs/res101_coco_2014_train+coco_2014_valminusminival__res101.txt.2018-02-04_14-10-46
+ set +x
+ '[' '!' -f output/res101/coco_2014_train+coco_2014_valminusminival/default/res101_faster_rcnn_iter_490000.ckpt.index ']'
+ [[ ! -z '' ]]
+ CUDA_VISIBLE_DEVICES=0
+ time python ./tools/trainval_net.py --weight data/imagenet_weights/res101.ckpt --imdb coco_2014_train+coco_2014_valminusminival --imdbval coco_2014_minival --iters 490000 --cfg experiments/cfgs/res101.yml --net res101 --set ANCHOR_SCALES '[4,8,16,32]' ANCHOR_RATIOS '[0.5,1,2]' TRAIN.STEPSIZE '[350000]'
Called with args:
Namespace(cfg_file='experiments/cfgs/res101.yml', imdb_name='coco_2014_train+coco_2014_valminusminival', imdbval_name='coco_2014_minival', max_iters=490000, net='res101', set_cfgs=['ANCHOR_SCALES', '[4,8,16,32]', 'ANCHOR_RATIOS', '[0.5,1,2]', 'TRAIN.STEPSIZE', '[350000]'], tag=None, weight='data/imagenet_weights/res101.ckpt')
Using config:
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [4, 8, 16, 32],
 'DATA_DIR': '/media/tensorflower/ExtraDrive1/tf-faster-rcnn/data',
 'EXP_DIR': 'res101',
 'MATLAB': 'matlab',
 'MOBILENET': {'DEPTH_MULTIPLIER': 1.0,
               'FIXED_LAYERS': 5,
               'REGU_DEPTH': False,
               'WEIGHT_DECAY': 4e-05},
 'PIXEL_MEANS': array([[[102.9801, 115.9465, 122.7717]]]),
 'POOLING_MODE': 'crop',
 'POOLING_SIZE': 7,
 'RESNET': {'FIXED_BLOCKS': 1, 'MAX_POOL': False},
 'RNG_SEED': 3,
 'ROOT_DIR': '/media/tensorflower/ExtraDrive1/tf-faster-rcnn',
 'RPN_CHANNELS': 512,
 'TEST': {'BBOX_REG': True,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'MODE': 'nms',
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'gt',
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'RPN_TOP_N': 5000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': False,
           'BATCH_SIZE': 256,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'BIAS_DECAY': False,
           'DISPLAY': 20,
           'DOUBLE_BIAS': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_KEPT': 3,
           'SNAPSHOT_PREFIX': 'res101_faster_rcnn',
           'STEPSIZE': [350000],
           'SUMMARY_INTERVAL': 180,
           'TRUNCATED': False,
           'USE_ALL_GT': True,
           'USE_FLIPPED': True,
           'USE_GT': False,
           'WEIGHT_DECAY': 0.0001},
 'USE_GPU_NMS': False}
loading annotations into memory...
Done (t=9.86s)
creating index...
index created!
Loaded dataset `coco_2014_train` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
wrote gt roidb to /media/tensorflower/ExtraDrive1/tf-faster-rcnn/data/cache/coco_2014_train_gt_roidb.pkl
done
Preparing training data...
done
loading annotations into memory...
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 105, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 76, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 76, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 69, in get_roidb
    imdb = get_imdb(imdb_name)
  File "/media/tensorflower/ExtraDrive1/tf-faster-rcnn/tools/../lib/datasets/factory.py", line 47, in get_imdb
    return __sets[name]()
  File "/media/tensorflower/ExtraDrive1/tf-faster-rcnn/tools/../lib/datasets/factory.py", line 34, in <lambda>
    __sets[name] = (lambda split=split, year=year: coco(split, year))
  File "/media/tensorflower/ExtraDrive1/tf-faster-rcnn/tools/../lib/datasets/coco.py", line 38, in __init__
    self._COCO = COCO(self._get_ann_file())
  File "/media/tensorflower/ExtraDrive1/tf-faster-rcnn/tools/../data/coco/PythonAPI/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: '/media/tensorflower/ExtraDrive1/tf-faster-rcnn/data/coco/annotations/instances_valminusminival2014.json'
Command exited with non-zero status 1
53.76user 2.84system 1:05.59elapsed 86%CPU (0avgtext+0avgdata 2748580maxresident)k
1113024inputs+80632outputs (1302major+894593minor)pagefaults 0swaps
```

**Comment by tensor-flower** [comment]
https://drive.google.com/drive/folders/0B1_fAEgxdnvJSmF3YUlZcHFqWTQ

It's here. Sorry I'm an idiot.

**Comment by sritank** [comment]
Refer here
https://github.com/rbgirshick/py-faster-rcnn/blob/master/data/README.md

They give the dropbox link as: https://dl.dropboxusercontent.com/s/s3tw5zcg7395368/instances_valminusminival2014.json.zip?dl=0.
