### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit__mask)

### ISSUE THREAD

**Issue by zyyhl** [endernewton/tf-faster-rcnn#324]
Traceback (most recent call last):
  File "./tools/test_net.py", line 13, in <module>
    from datasets.factory import get_imdb
  File "/home/user/zyy/tf-faster-rcnn-master/tools/../lib/datasets/factory.py", line 15, in <module>
    from datasets.coco import coco
  File "/home/user/zyy/tf-faster-rcnn-master/tools/../lib/datasets/coco.py", line 23, in <module>
    from pycocotools.coco import COCO
  File "/home/user/zyy/tf-faster-rcnn-master/tools/../data/coco/PythonAPI/pycocotools/coco.py", line 55, in <module>
    from . import mask as maskUtils
  File "/home/user/zyy/tf-faster-rcnn-master/tools/../data/coco/PythonAPI/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
ImportError: dynamic module does not define module export function (PyInit__mask)

**Comment by ninesky110** [comment]
python setup.py and you can have two .so files ,then put the file in nms file and untils
