### ISSUE TITLE
error when testing with pre-trained Resnet101 models

### ISSUE THREAD

**Issue by Iric2018** [endernewton/tf-faster-rcnn#329]
when I run ./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101, the error happened as following:
......
im_detect: 4946/4952 0.108s 0.029s
im_detect: 4947/4952 0.108s 0.029s
im_detect: 4948/4952 0.108s 0.029s
im_detect: 4949/4952 0.108s 0.029s
im_detect: 4950/4952 0.108s 0.029s
im_detect: 4951/4952 0.108s 0.029s
im_detect: 4952/4952 0.108s 0.029s
Evaluating detections
Writing aeroplane VOC results file
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/hust/tf-faster-rcnn-master/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/hust/tf-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 282, in evaluate_detections
    self._write_voc_results_file(all_boxes)
  File "/home/hust/tf-faster-rcnn-master/tools/../lib/datasets/pascal_voc.py", line 209, in _write_voc_results_file
    with open(filename, 'wt') as f:
IOError: [Errno 2] No such file or directory: '/home/hust/tf-faster-rcnn-master/data/VOCdevkit2007/results/VOC2007/Main/comp4_e723652d-d720-4125-a6d6-9ef3078bb80b_det_test_aeroplane.txt'
Command exited with non-zero status 1
564.38user 174.51system 11:41.10elapsed 105%CPU (0avgtext+0avgdata 1700188maxresident)k
0inputs+27376outputs (0major+366474minor)pagefaults 0swaps
(tf-faster-rcnn) hust@hust-System-Product-Name:~/tf-faster-rcnn-master$

**Comment by TipsyApple** [comment]
please refer to #246

**Comment by ChengxiHAN** [comment]
1.when I run：
GPU_ID=0
./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101
the error happened as following:
......
Traceback (most recent call last):
  File "./tools/test_net.py", line 67, in <module>
    cfg_from_list(args.set_cfgs)
  File "/home/lc/Desktop/Han/API/tf-faster-rcnn-master/tools/../lib/model/config.py", line 386, in cfg_from_list
    type(value), type(d[subkey]))
AssertionError: type <class 'int'> does not match original type <class 'list'>
Command exited with non-zero status 1
1.52user 0.39system 0:01.62elapsed 118%CPU (0avgtext+0avgdata 270240maxresident)k
0inputs+8outputs (0major+81935minor)pagefaults 0swaps

please tell me the details of  solving this error.

2.I have succeed in testing demo,but maybe there is one question as following:
CUDA driver version is insufficient for CUDA runtime version
...

**Comment by rnsandeep** [comment]
You have to create a directory structure like this /home/hust/tf-faster-rcnn-master/data/VOCdevkit2007/results/VOC2007/Main/ 
Then it will save the file in the location.

**Comment by rnsandeep** [comment]
You need to update nvidia driver and install cuda with sufficient version.
