### ISSUE TITLE
error occurs when I try to train res101 on my own data

### ISSUE THREAD

**Issue by chenyuqing** [endernewton/tf-faster-rcnn#344]
/home/honghaier1688/.local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Loading initial model weights from data/imagenet_weights/res101.ckpt
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for data/imagenet_weights/res101.ckpt
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 139, in <module>
    max_iters=args.max_iters)
  File "/home/honghaier1688/workspaces/tf-faster-rcnn/tools/../lib/model/train_val.py", line 377, in train_net
    sw.train_model(sess, max_iters)
  File "/home/honghaier1688/workspaces/tf-faster-rcnn/tools/../lib/model/train_val.py", line 255, in train_model
    rate, last_snapshot_iter, stepsizes, np_paths, ss_paths = self.initialize(sess)
  File "/home/honghaier1688/workspaces/tf-faster-rcnn/tools/../lib/model/train_val.py", line 188, in initialize
    variables_to_restore = self.net.get_variables_to_restore(variables, var_keep_dic)
  File "/home/honghaier1688/workspaces/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 162, in get_variables_to_restore
    if v.name.split(':')[0] in var_keep_dic:
TypeError: argument of type 'NoneType' is not iterable
Command exited with non-zero status 1

**Comment by chenyuqing** [comment]
I fixed it, because the name of pre-trained model is wrong, I send the argument whose name is res101 but the true model on my disk is resnet101, that is it.

**Comment by MarkLei1** [comment]
thanks!
