### ISSUE TITLE
 No variables to save

### ISSUE THREAD

**Issue by struCoder** [endernewton/tf-faster-rcnn#349]
I follow your steps and it is already trained. I wish to restore it to run it on a few samples but unfortunately its spitting out:
[demo.py](https://gist.github.com/struCoder/7b09df5b37956f237f8e962b5b1f8ed5)
```bash
Traceback (most recent call last):
  File "tools/demo.py", line 139, in <module>
    load_tf_model('output/vgg16/voc_2007_trainval/default/', im_name)
  File "tools/demo.py", line 119, in load_tf_model
    saver = tf.train.Saver()
  File "/home/bigdata/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/bigdata/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/bigdata/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1251, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

My code:
```python
cfg.TEST.HAS_RPN = True  # Use RPN for proposals
config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.per_process_gpu_memory_fraction = 0.6
sess = tf.Session(config=config)
net = vgg16()
with sess.graph.as_default():
    saver = tf.train.Saver()
    ckpt = tf.train.get_checkpoint_state(ckpt_dir)
    saver.restore(sess, ckpt.model_checkpoint_path)
    demo(sess, net, im_name)
    plt.savefig('aa.png')
```

If i recover by this code:
```python
    cfg.TEST.HAS_RPN = True  # Use RPN for proposals
    config = tf.ConfigProto(allow_soft_placement=True)
    config.gpu_options.per_process_gpu_memory_fraction = 0.6
    sess = tf.Session(config=config)
    net = vgg16()
    saver = tf.train.import_meta_graph('output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_10000.ckpt.meta')
    saver.restore(sess, tf.train.latest_checkpoint('output/vgg16/voc_2007_trainval/default/'))

    #saver = tf.train.Saver()
    #ckpt = tf.train.get_checkpoint_state(ckpt_dir)
    #saver.restore(sess, ckpt.model_checkpoint_path)
    demo(sess, net, im_name)
    plt.savefig('aa.png')
```

I got this error:
```bash

Traceback (most recent call last):
  File "tools/demo.py", line 138, in <module>
    load_tf_model('output/vgg16/voc_2007_trainval/default/', im_name)
  File "tools/demo.py", line 123, in load_tf_model
    demo(sess, net, im_name)
  File "tools/demo.py", line 80, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/bigdata/ky/rider_box_detector2/tools/../lib/model/test.py", line 93, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/home/bigdata/ky/rider_box_detector2/tools/../lib/nets/network.py", line 471, in test_image
    feed_dict = {self._image: image,
AttributeError: 'vgg16' object has no attribute '_image'

```

**Comment by struCoder** [comment]
solved this problem.
Because i deleted this line`net.create_architecture("TEST", 21, tag='default', anchor_scales=[8, 16, 32])`

**Comment by buaaYYC** [comment]
> solved this problem.
> Because i deleted this line`net.create_architecture("TEST", 21, tag='default', anchor_scales=[8, 16, 32])`
net.create_architecture("TEST", 21, tag='default', anchor_scales=[8, 16, 32]) , i want to kown which py file
