### ISSUE TITLE
test  error in excuting  task of  './experiments/scripts/test_faster_rcnn.sh 0 pascal_voc vgg16 '

### ISSUE THREAD

**Issue by ccywxhn** [endernewton/tf-faster-rcnn#405]
Evaluating detections
Writing car VOC results file
VOC07 metric? Yes
Reading annotation for 1/637
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/ccy/fasterrcnn/tf-faster-rcnn/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/ccy/fasterrcnn/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 284, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/ccy/fasterrcnn/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 247, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "/home/ccy/fasterrcnn/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 115, in voc_eval
    recs[imagename] = parse_rec(annopath.format(imagename))
  File "/home/ccy/fasterrcnn/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 23, in parse_rec
    obj_struct['truncated'] = int(obj.find('truncated').text)
ValueError: invalid literal for int() with base 10: '0.0597'
Command exited with non-zero status 1
50.86user 8.38system 1:12.69elapsed 81%CPU (0avgtext+0avgdata 3430092maxresident)k
8inputs+5512outputs (0major+1799780minor)pagefaults 0swaps

**Comment by zyuerugou** [comment]
in the annotations/*.xml, <truncated>x</truncated>
x must be 0 or 1 @ccywxhn

**Comment by zyuerugou** [comment]
@ccywxhn 
str->float->int
'0.0597'->int  is invalid
obj_struct['truncated'] = int(float(obj.find('truncated').text))  will be ok

**Comment by ccywxhn** [comment]
Thank you for your answer, the problem has been solved.




------------------ 原始邮件 ------------------
发件人: "zyuerugou"<notifications@github.com>; 
发送时间: 2019年5月2日(星期四) 晚上9:39
收件人: "endernewton/tf-faster-rcnn"<tf-faster-rcnn@noreply.github.com>; 
抄送: "Ccy"<1103495664@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [endernewton/tf-faster-rcnn] testing  error of own dataset  inexcuting  task of  './experiments/scripts/test_faster_rcnn.sh 0 pascal_vocvgg16 ' (#405)




@ccywxhn
 str->float->int
 '0.0597'->int  is invalid
 obj_struct['truncated'] = int(float(obj.find('truncated').text))  will be ok
