### ISSUE TITLE
There is a problem in the test link after the training. It should be what the previous test file saved. After the data and test file are replaced, an error is reported.

### ISSUE THREAD

**Issue by huaxv** [endernewton/tf-faster-rcnn#422]
Writing person VOC results file
Writing motorbike VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 120, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/amax/yang4/zgaibug/tf-faster-rcnn/tools/../lib/model/test.py", line 192, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/amax/yang4/zgaibug/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 279, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/amax/yang4/zgaibug/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 242, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "/home/amax/yang4/zgaibug/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 135, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '000006'
Command exited with non-zero status 1
2539.85user 176.37system 3:04.95elapsed 1468%CPU (0avgtext+0avgdata 2184836maxresident)k
0inputs+10608outputs (0major+1000596minor)pagefaults 0swaps

**Comment by shirleyatgithub** [comment]
Hi, huaxv,
I have encountered the same error as yours. Have you solved this problem? could you tell me how to?
