### ISSUE TITLE
generate_anchors_pre() argument mismatch

### ISSUE THREAD

**Issue by aakashkhochare** [endernewton/tf-faster-rcnn#44]
While running the demo, I face the following issue with generate_anchors_pre(). The tensorflow version I am using is 1.0.1

Demo for data/demo/000456.jpg
Traceback (most recent call last):
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
TypeError: generate_anchors_pre() takes exactly 5 arguments (4 given)
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_0: see error log.
Traceback (most recent call last):
  File "./tools/demo_depre.py", line 152, in <module>
    demo(sess, net, im_name)
  File "./tools/demo_depre.py", line 83, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/aakhochare/VisualAlgorithms/tf-faster-rcnn/tools/../lib/model/test_vgg16.py", line 90, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/home/aakhochare/VisualAlgorithms/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 532, in test_image
    feed_dict=feed_dict)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_0: see error log.
	 [[Node: vgg16_default/ANCHOR_default/generate_anchors = PyFunc[Tin=[DT_INT32, DT_INT32, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_INT32], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg16_default/ANCHOR_default/ToInt32, vgg16_default/ANCHOR_default/ToInt32_1, vgg16_default/ANCHOR_default/generate_anchors/input_2, vgg16_default/ANCHOR_default/generate_anchors/input_3)]]

Caused by op u'vgg16_default/ANCHOR_default/generate_anchors', defined at:
  File "./tools/demo_depre.py", line 141, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "/home/aakhochare/VisualAlgorithms/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 484, in create_architecture
    rois, cls_prob, bbox_pred = self._vgg16_from_imagenet(sess, training)
  File "/home/aakhochare/VisualAlgorithms/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 346, in _vgg16_from_imagenet
    self._anchor_component()
  File "/home/aakhochare/VisualAlgorithms/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 293, in _anchor_component
    [tf.float32, tf.int32], name="generate_anchors")
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_0: see error log.
	 [[Node: vgg16_default/ANCHOR_default/generate_anchors = PyFunc[Tin=[DT_INT32, DT_INT32, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_INT32], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg16_default/ANCHOR_default/ToInt32, vgg16_default/ANCHOR_default/ToInt32_1, vgg16_default/ANCHOR_default/generate_anchors/input_2, vgg16_default/ANCHOR_default/generate_anchors/input_3)]]

**Comment by endernewton** [comment]
This is probably because of the recent updates on anchor aspect ratios.. @philokey will fix it soon. in the mean time, you can check demo.py with resnet.

**Comment by endernewton** [comment]
updated. should have fixed the problem.

**Comment by aakashkhochare** [comment]
Well, got past the generate_anchors_pre() but now you have an argument mismatch with proposal_top_layer(), in the mean time I am using the demo.py

Demo for data/demo/000456.jpg
Traceback (most recent call last):
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
TypeError: proposal_top_layer() takes exactly 7 arguments (6 given)
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_1: see error log.
Traceback (most recent call last):
  File "./tools/demo_depre.py", line 152, in <module>
    demo(sess, net, im_name)
  File "./tools/demo_depre.py", line 83, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/aakhochare/FasterRCNN/tf-faster-rcnn/tools/../lib/model/test_vgg16.py", line 90, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/home/aakhochare/FasterRCNN/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 532, in test_image
    feed_dict=feed_dict)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_1: see error log.
	 [[Node: vgg16_default/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg16_default/rpn_cls_prob/transpose_1, vgg16_default/rpn_bbox_pred/BiasAdd, _recv_Placeholder_1_0, vgg16_default/rois/PyFunc/input_3, vgg16_default/ANCHOR_default/generate_anchors, vgg16_default/rois/PyFunc/input_5)]]

Caused by op u'vgg16_default/rois/PyFunc', defined at:
  File "./tools/demo_depre.py", line 141, in <module>
    tag='default', anchor_scales=[8, 16, 32])
  File "/home/aakhochare/FasterRCNN/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 484, in create_architecture
    rois, cls_prob, bbox_pred = self._vgg16_from_imagenet(sess, training)
  File "/home/aakhochare/FasterRCNN/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 368, in _vgg16_from_imagenet
    rois, _ = self._proposal_top_layer(rpn_cls_prob, rpn_bbox_pred, "rois")
  File "/home/aakhochare/FasterRCNN/tf-faster-rcnn/tools/../lib/nets/vgg16_depre.py", line 200, in _proposal_top_layer
    self._feat_stride, self._anchors, self._anchor_scales], [tf.float32, tf.float32])
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/aakhochare/tensorflowr10/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_1: see error log.
	 [[Node: vgg16_default/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg16_default/rpn_cls_prob/transpose_1, vgg16_default/rpn_bbox_pred/BiasAdd, _recv_Placeholder_1_0, vgg16_default/rois/PyFunc/input_3, vgg16_default/ANCHOR_default/generate_anchors, vgg16_default/rois/PyFunc/input_5)]]

**Comment by endernewton** [comment]
Should be fixed now.

**Comment by aakashkhochare** [comment]
Yes. Fixed! Thanks
