### ISSUE TITLE
shape not found when finetune

### ISSUE THREAD

**Issue by Yiman-GO** [endernewton/tf-faster-rcnn#441]
I got an error when I use .
./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc res101 USE_GPU_NMS False .
The error is as follows:
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 110, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 77, in combined_roidb
    roidb = get_roidb(imdb_names.split('+')[0])
  File "./tools/trainval_net.py", line 73, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/zfit/PycharmProjects/TENSORFLOW/tf-faster-rcnn_disc/tools/../lib/model/train_val.py", line 332, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/zfit/PycharmProjects/TENSORFLOW/tf-faster-rcnn_disc/tools/../lib/roi_data_layer/roidb.py", line 38, in prepare_roidb
    gt_overlaps = roidb[i][b'gt_overlaps'].toarray()
  File "/home/zfit/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 962, in toarray
    out = self._process_toarray_args(order, out)
  File "/home/zfit/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/sparse/base.py", line 1187, in _process_toarray_args
    return np.zeros(self.shape, dtype=self.dtype, order=order)
  File "/home/zfit/anaconda3/envs/tensorflow/lib/python3.6/site-packages/scipy/sparse/base.py", line 689, in __getattr__
    raise AttributeError(attr + " not found")
AttributeError: shape not found

**Comment by Yiman-GO** [comment]
I have tried print(roidb[i][b'gt_overlaps']), got "shape not found" too. 
Does anyone know why?
