### ISSUE TITLE
TypeError: write() argument must be str, not bytes

### ISSUE THREAD

**Issue by henbucuoshanghai** [endernewton/tf-faster-rcnn#452]

**Comment by henbucuoshanghai** [comment]
File "/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 246, in _do_python_eval
    use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
  File "/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 122, in voc_eval
    pickle.dump(recs, f)
TypeError: write() argument must be str, not bytes
Command exited with non-zero status 1
2484.50user 101.77system 7:44.19elapsed 557%CPU (0avgtext+0avgdata 2846360maxresident)k
1296inputs+62952outputs (4major+7864686minor)pagefaults 0swaps

**Comment by henbucuoshanghai** [comment]
./experiments/scripts/test_faster_rcnn.sh $GPU_ID pascal_voc_0712 res101

**Comment by TakedaHiroki** [comment]
Hi, @henbucuoshanghai 

You can probably solve this error and another error coused by changing as follows:

Edit tf-faster-rcnn/lib/datasets/voc_eval.py 

line121, change 'w' to 'wb' like this

    with open(cachefile, 'wb') as f:
  

line105, change to 

    cachefile = os.path.join(cachedir, '%s_annots.pkl' % imagesetfile.split("/")[-1].split(".")[0])

**Comment by cracyling** [comment]
Hi, @TakedaHiroki  
Thanks for the help. Your solution solve the error. 
But because we modify the cachefile. 

Another error prompt out. 

> UnboundLocalError: local variable 'cachefile' referenced before assignment


Below are the lines after im_detect and before the error prompt out. 

 
> im_detect: 4952/4952 0.129s 0.003s
> Evaluating detections
> Writing aeroplane VOC results file
> Writing bicycle VOC results file
> Writing bird VOC results file
> Writing boat VOC results file
> Writing bottle VOC results file
> Writing bus VOC results file
> Writing car VOC results file
> Writing cat VOC results file
> Writing chair VOC results file
> Writing cow VOC results file
> Writing diningtable VOC results file
> Writing dog VOC results file
> Writing horse VOC results file
> Writing motorbike VOC results file
> Writing person VOC results file
> Writing pottedplant VOC results file
> Writing sheep VOC results file
> Writing sofa VOC results file
> Writing train VOC results file
> Writing tvmonitor VOC results file
> VOC07 metric? Yes
> Traceback (most recent call last):
>   File "./tools/test_net.py", line 120, in <module>
>     test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
>   File "/home/siw/pyenvtest/tf-faster-rcnn/tools/../lib/model/test.py", line 192, in test_net
>     imdb.evaluate_detections(all_boxes, output_dir)
>   File "/home/siw/pyenvtest/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 283, in evaluate_detections
>     self._do_python_eval(output_dir)
>   File "/home/siw/pyenvtest/tf-faster-rcnn/tools/../lib/datasets/pascal_voc.py", line 246, in _do_python_eval
>     use_07_metric=use_07_metric, use_diff=self.config['use_diff'])
>   File "/home/siw/pyenvtest/tf-faster-rcnn/tools/../lib/datasets/voc_eval.py", line 112, in voc_eval
>     if not os.path.isfile(cachefile):
> UnboundLocalError: local variable 'cachefile' referenced before assignment
> Command exited with non-zero status 1

**Comment by TakedaHiroki** [comment]
@henbucuoshanghai
Is 'cachefile' defined correctly?
Can you show me your code?

**Comment by cracyling** [comment]
@TakedaHiroki 

I replaced the same code as your suggestion on line 121 and line 105.

Another error arise after modify based on your suggestion. 

> UnboundLocalError: local variable 'cachefile' referenced before assignment
> Command exited with non-zero status 1
> 496.91user 96.31system 11:20.82elapsed 87%CPU (0avgtext+0avgdata 2755916maxresident)k
> 870344inputs+62736outputs (2major+4984217minor)pagefaults 0swaps
> 

![image](https://user-images.githubusercontent.com/54388013/64141236-d5fb8880-ce39-11e9-90f9-72f6b6600485.png)

**Comment by Hajarat** [comment]
Hey @TakedaHiroki, I'm still getting this error even with the updated code. What do you reckon?
