### ISSUE TITLE
ValueError: The passed save_path is not a valid checkpoint: 

### ISSUE THREAD

**Issue by wudi00** [endernewton/tf-faster-rcnn#469]
When I test the trained model, there is such error, why? Thanks
`Traceback (most recent call last):
  File "./tools/test_net.py", line 113, in <module>
    saver.restore(sess, args.model)
  File "/media/disk/wudi/.local/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    + compat.as_text(save_path))
ValueError: The passed save_path is not a valid checkpoint: output/vgg16/voc_2007_trainval/default/vgg16_faster_rcnn_iter_1000.ckpt
`

**Comment by Katherinaxxx** [comment]
Hey, how did you solve the problem? Can you please share?

**Comment by Macile** [comment]
how did you solve the problem? Can you please share?thank  you very much
