### ISSUE TITLE
Docker appears to be using Ubuntu 16.04 and python 2.7 with the latest pip which would cause a syntax Error.

### ISSUE THREAD

**Issue by atursams** [endernewton/tf-faster-rcnn#507]
Hi,
I tried to build the docker `Dockerfile.cuda-8.0` and it failed like so:

```
Step 5/14 : RUN pip install image                 scipy                 matplotlib                 PyYAML                 numpy                 easydict                 tensorflow-gpu
 ---> Running in 9fc5d4e836d5
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

This is what I did to use a recent version of python:

```
.
.
# Get required python modules
RUN pip install --upgrade pip==20.3.4
```

You get warnings but the code runs.

**Comment by atursams** [comment]
I made the changes but I still cannot use the resulting docker image even though it was able to run.
