### ISSUE TITLE
How to fine tuning?

### ISSUE THREAD

**Issue by wang-tf** [endernewton/tf-faster-rcnn#52]
I don't know how to finetuning. I had changed the file of pascal_voc.py. But there was an error when I was running `./experiments/scripts/train_faster_rcnn.sh 0 pascal_voc vgg16`  
>Loaded dataset `voc_2007_trainval` for training
Set proposal method: gt
Appending horizontally-flipped training examples...
voc_2007_trainval gt roidb loaded from /home/weiguang/tf-faster-rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 105, in <module>
    imdb, roidb = combined_roidb(args.imdb_name)
  File "./tools/trainval_net.py", line 76, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "./tools/trainval_net.py", line 73, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/home/weiguang/tf-faster-rcnn/tools/../lib/model/train_val.py", line 303, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/weiguang/tf-faster-rcnn/tools/../lib/datasets/imdb.py", line 120, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError
Command exited with non-zero status 1
1.81user 0.51system 0:02.35elapsed 98%CPU (0avgtext+0avgdata 303112maxresident)k
168inputs+56outputs (0major+56787minor)pagefaults 0swaps

**Comment by wang-tf** [comment]
I forgot to delete the files in data/cache. It's well when I had deleted these files.
