### ISSUE TITLE
Error during training after 7120 iterations

### ISSUE THREAD

**Issue by chakpongchung** [endernewton/tf-faster-rcnn#70]
./experiments/scripts/train_faster_rcnn.sh 1 pascal_voc vgg16 USE_GPU_NMS False

to run this command with the VOC2007 data downloaded, I need to manually set 

# Images to use per minibatch
__C.TRAIN.IMS_PER_BATCH = 1

Is that expected?

**Comment by chakpongchung** [comment]
Even I change the minibatch to 1, I have the following problem

device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:04:00.0)
Solving...
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 131, in <module>
    max_iters=args.max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 378, in train_net
    sw.train_model(sess, max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 105, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 324, in create_architecture
    val_summaries.append(self._add_image_summary(self._image, self._gt_boxes))
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 56, in _add_image_summary
    assert image.get_shape()[0] == 1
AssertionError
Command exited with non-zero status 1

**Comment by endernewton** [comment]
maybe the ultimate problem on your side is the parameters are not set. check your installation with easydict? a different version may be needed.

**Comment by chakpongchung** [comment]
Thank you for your feedback!

Finally I found out the problem. Some of my bounding boxes is too close to the boundary of the image size. So I only keep those bounding boxes that are within the "center of the image" plus/miuns 0.3*(width/height).

Then I have a new problem:

iter: 7110 / 10000, total loss: 0.273753
 >>> rpn_loss_cls: 0.062352
 >>> rpn_loss_box: 0.022567
 >>> loss_cls: 0.150609
 >>> loss_box: 0.038224
 >>> lr: 0.001000
speed: 0.682s / iter
iter: 7120 / 10000, total loss: 0.218106
 >>> rpn_loss_cls: 0.026532
 >>> rpn_loss_box: 0.028579
 >>> loss_cls: 0.097216
 >>> loss_box: 0.065779
 >>> lr: 0.001000
speed: 0.682s / iter
Traceback (most recent call last):
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/layer_utils/anchor_target_layer.py", line 53, in anchor_target_layer
    gt_argmax_overlaps = overlaps.argmax(axis=0)
ValueError: attempt to get argmax of an empty sequence
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 381, in train_net
    sw.train_model(sess, max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 280, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 374, in train_step
    feed_dict=feed_dict)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: vgg_16/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_score/BiasAdd/_195, _recv_Placeholder_2_0, _recv_Placeholder_1_0, vgg_16/anchor/PyFunc/input_3, vgg_16/ANCHOR_default/generate_anchors, vgg_16/anchor/PyFunc/input_5)]]
	 [[Node: vgg_16/rpn_rois/PyFunc/_245 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1112_vgg_16/rpn_rois/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'vgg_16/anchor/PyFunc', defined at:
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 381, in train_net
    sw.train_model(sess, max_iters)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 105, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 305, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 68, in build_network
    rpn_labels = self._anchor_target_layer(rpn_cls_score, "anchor")
  File "/local/d2/users/310195626/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 149, in _anchor_target_layer
    [tf.float32, tf.float32, tf.float32, tf.float32])
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/310270534/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_2: see error log.
	 [[Node: vgg_16/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_score/BiasAdd/_195, _recv_Placeholder_2_0, _recv_Placeholder_1_0, vgg_16/anchor/PyFunc/input_3, vgg_16/ANCHOR_default/generate_anchors, vgg_16/anchor/PyFunc/input_5)]]
	 [[Node: vgg_16/rpn_rois/PyFunc/_245 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1112_vgg_16/rpn_rois/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Command exited with non-zero status 1
4403.58user 609.60system 1:21:16elapsed 102%CPU (0avgtext+0avgdata 4245508maxresident)k
7384inputs+2181040outputs (9major+39293420minor)pagefaults 0swaps

Could you share some insight about this debug info?

**Comment by chakpongchung** [comment]
I used another computer with two 1080TI. The problem can be  reproduced as follow:

rm -r data/cache/
rm -rf ~/experiments/tf-faster-rcnn/output/*
./experiments/scripts/train_faster_rcnn.sh 1 pascal_voc vgg16 

Traceback (most recent call last):
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/layer_utils/anchor_target_layer.py", line 53, in anchor_target_layer
    gt_argmax_overlaps = overlaps.argmax(axis=0)
ValueError: attempt to get argmax of an empty sequence
2017-05-02 16:33:17.825967: W tensorflow/core/framework/op_kernel.cc:1152] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 381, in train_net
    sw.train_model(sess, max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 280, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 374, in train_step
    feed_dict=feed_dict)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: vgg_16/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_score/BiasAdd/_119, _recv_Placeholder_2_0, _recv_Placeholder_1_0, vgg_16/anchor/PyFunc/input_3, vgg_16/ANCHOR_default/generate_anchors, vgg_16/anchor/PyFunc/input_5)]]
	 [[Node: gradients/loss_default/mul_4_grad/Shape/_129 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1340_gradients/loss_default/mul_4_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'vgg_16/anchor/PyFunc', defined at:
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 381, in train_net
    sw.train_model(sess, max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 105, in train_model
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 305, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/nets/vgg16.py", line 68, in build_network
    rpn_labels = self._anchor_target_layer(rpn_cls_score, "anchor")
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 149, in _anchor_target_layer
    [tf.float32, tf.float32, tf.float32, tf.float32])
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_2: see error log.
	 [[Node: vgg_16/anchor/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](vgg_16/rpn_cls_score/BiasAdd/_119, _recv_Placeholder_2_0, _recv_Placeholder_1_0, vgg_16/anchor/PyFunc/input_3, vgg_16/ANCHOR_default/generate_anchors, vgg_16/anchor/PyFunc/input_5)]]
	 [[Node: gradients/loss_default/mul_4_grad/Shape/_129 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_1340_gradients/loss_default/mul_4_grad/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Command exited with non-zero status 1
1635.65user 224.85system 30:52.94elapsed 100%CPU (0avgtext+0avgdata 4098292maxresident)k
3008496inputs+2410904outputs (1475major+1074846minor)pagefaults 0swaps

**Comment by chakpongchung** [comment]
problem solved by leaving margin btw image and bounding boxes

**Comment by satya2550** [comment]
I also got the same error, but i did not understand the given answer
problem solved by leaving margin btw image and bounding boxes.
Can you please explain.

**Comment by komejisatori** [comment]
in my case, this is because your dataset contains imgs which has no positive boxes, check your xml file or your classes name in pascal_voc.py
