### ISSUE TITLE
Problem with Proposal_layer : TypeError: 'NoneType' object has no attribute 'getitem'

### ISSUE THREAD

**Issue by vasilgeorge** [endernewton/tf-faster-rcnn#76]
Hi! When I try to test the network I get the following errors:

Traceback (most recent call last):
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 82, in __call__
    ret = func(*args)
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/layer_utils/proposal_layer.py", line 46, in proposal_layer
    keep = keep[:post_nms_topN]
TypeError: 'NoneType' object has no attribute '__getitem__'
W tensorflow/core/framework/op_kernel.cc:993] Internal: Failed to run py callback pyfunc_1: see error log.
Traceback (most recent call last):
  File "./tools/test_net.py", line 138, in <module>
    test_net(sess, net, imdb, filename, max_per_image=args.max_per_image)
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/model/test.py", line 160, in test_net
    scores, boxes = im_detect(sess, net, im)
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/model/test.py", line 96, in im_detect
    _, scores, bbox_pred, rois = net.test_image(sess, blobs['data'], blobs['im_info'])
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/nets/network.py", line 355, in test_image
    feed_dict=feed_dict)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_1: see error log.
	 [[Node: resnet_v1_101_3/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOA]

Caused by op u'resnet_v1_101_3/rois/PyFunc', defined at:
  File "./tools/test_net.py", line 126, in <module>
    anchor_ratios=cfg.ANCHOR_RATIOS)
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/nets/network.py", line 305, in create_architecture
    rois, cls_prob, bbox_pred = self.build_network(sess, training)
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/nets/resnet_v1.py", line 201, in build_network
    rois, _ = self._proposal_layer(rpn_cls_prob, rpn_bbox_pred, "rois")
  File "/home/user/Desktop/Diploma Thesis/Pre-Trained/tf-faster-rcnn/tools/../lib/nets/network.py", line 109, in _proposal_layer
    [tf.float32, tf.float32])
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 189, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/user/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_1: see error log.
	 [[Node: resnet_v1_101_3/rois/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_STRING, DT_INT32, DT_FLOAT, DT_INT32], Tout=[DT_FLOA]

Command exited with non-zero status 1
36.86user 2.62system 0:44.07elapsed 89%CPU (0avgtext+0avgdata 616096maxresident)k
526184inputs+32outputs (656major+892344minor)pagefaults 0swaps

Any ideas?

**Comment by vasilgeorge** [comment]
I faced this issue while making the cpu version of Faster R-CNN. The The issue was due to a wrong nms return from the nms wrapper.

Editing the nms_wrapper.py in /lib/model fixed the problem for me [:](https://github.com/rbgirshick/py-faster-rcnn/issues/229)

```
def nms(dets, thresh, force_cpu=False):
   #Dispatch to either CPU or GPU NMS implementations.

    if dets.shape[0] == 0:
        return []
    if cfg.USE_GPU_NMS and not force_cpu:
        #return gpu_nms(dets, thresh, device_id=cfg.GPU_ID)
        return cpu_nms(dets, thresh)
    else:
        return cpu_nms(dets, thresh)

```

**Comment by bhack** [comment]
Can you create a PR?
