### ISSUE TITLE
Is the COCO resnet model released?

### ISSUE THREAD

**Issue by hqqxyy** [endernewton/tf-faster-rcnn#87]
Hi,

Many thanks to you and it is really a great work!

I try to finetune COCO resnet101 model for other tasks. To make life easier, I try to download them. But I can not find it in http://gs11655.sp.cs.cmu.edu/xinleic/tf-faster-rcnn/ and https://drive.google.com/drive/folders/0B1_fAEgxdnvJSmF3YUlZcHFqWTQ

I also try to search them in google and githbu. But I do not find them.

So I want to know if the COCO resnet model is released? And would you mind giving me a download link? 

Thanks a lot.

**Comment by endernewton** [comment]
since i have received lots of request for putting up coco resnet models, i have just uploaded one (with a single attempt of training) for res101. you can check it out. note that i am still trying to verify training schedules/hyperparameters  to get a good speed/accuracy tradeoff after recent updates, so the model can get updated later (with better AP).

**Comment by JRCondeNast** [comment]
Original Demo works fine.
I tried pre-trained model on coco resnet and vgg16 model uploaded to google drive. 
I changed demo.py:CLASSES = ('__background__','person','bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch', 'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')

NETS = {'vgg16': ('vgg16_faster_rcnn_iter_1190000.ckpt',),'res101': ('res101_fas
ter_rcnn_iter_1190000.ckpt',)}
DATASETS= {'coco_2014': ('coco_2014_train+coco_2014_valminusminival',)}

also for create_architecture, change classes to 81.
Got the following error:
Traceback (most recent call last):
  File "./tools/demo_coco.py", line 146, in <module>
    saver.restore(sess, tfmodel)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,1,512,18] rhs shape= [1,1,512,24]
	 [[Node: save/Assign_37 = Assign[T=DT_FLOAT, _class=["loc:@vgg_16/rpn_cls_score/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/rpn_cls_score/weights, save/RestoreV2_37/_23)]]

Caused by op 'save/Assign_37', defined at:
  File "./tools/demo_coco.py", line 145, in <module>
    saver = tf.train.Saver()
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/jren/miniconda3/envs/test_faster_rcnn/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [1,1,512,18] rhs shape= [1,1,512,24]
	 [[Node: save/Assign_37 = Assign[T=DT_FLOAT, _class=["loc:@vgg_16/rpn_cls_score/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/rpn_cls_score/weights, save/RestoreV2_37/_23)]]

**Comment by wyman-Y** [comment]
hello, I meet the same problem. Could you tell me how to solve it? @JRCondeNast
