### ISSUE TITLE
use batch size to be 2

### ISSUE THREAD

**Issue by chakpongchung** [endernewton/tf-faster-rcnn#88]
The default code does not run using 2 as the batch size. So I changed it to be 1 in config.py and it runs.

I changed it back to 2 and get rid of some assertions. I saw the following. Do I need to touch the tensorflow code itself?

Traceback (most recent call last):
  File "./tools/trainval_net.py", line 136, in <module>
    max_iters=args.max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 381, in train_net
    sw.train_model(sess, max_iters)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/model/train_val.py", line 280, in train_model
    self.net.train_step(sess, blobs, train_op)
  File "/local/home/cpchung/experiments/tf-faster-rcnn/tools/../lib/nets/network.py", line 375, in train_step
    feed_dict=feed_dict)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/local/home/cpchung/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 961, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
**ValueError: Cannot feed value of shape (1, 3) for Tensor u'Placeholder_1:0', which has shape '(2, 3)'**
Command exited with non-zero status 1

**Comment by endernewton** [comment]
it is not recommended to use a image batch size of more than 1, you need to do a lot of change there. writing code for iter_size > 1 (with some overhead in gpu memory) is a better way to go in my mind.

**Comment by chakpongchung** [comment]
Thanks! Just curious, the faster rcnn paper mentioned the experiment  to set the batch size to be 2,

did I understand it correctly? the code pulled down from your repository also makes it to be 2

**Comment by endernewton** [comment]
that's because the itersize is 2

---------------------
Ender X. Chen

Language Technologies Institute,
School of Computer Science,
Carnegie Mellon University, Pittsburgh, PA

**Comment by akczay** [comment]
Can you tell me where I can find iter_size? In the original code, it's in the solver file. Do you mean we need to change `__C.TRAIN.IMS_PER_BATCH = 1` in `lib/model/config.py` to have multiple images in the batch?

**Comment by ranjana-raveesh** [comment]
InvalidArgumentError: Input to reshape is a tensor with 20 values, but the requested shape has 84
	 [[Node: save/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](save/RestoreV2/_79, save/Reshape/shape)]]

Caused by op u'save/Reshape', defined at:
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 866, in start
    handler_func(fd_obj, events)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-24c9450db07e>", line 144, in <module>
    saver = tf.train.Saver(tf.all_variables(), reshape=True)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 150, in restore
    restored_tensor = array_ops.reshape(restored_tensor, restored_shapes[0])
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2510, in reshape
    name=name)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/opt/DL/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Input to reshape is a tensor with 20 values, but the requested shape has 84
	 [[Node: save/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"](save/RestoreV2/_79, save/Reshape/shape)]]
